### PR TITLE
Fix parser of image tags

### PR DESCRIPTION
**Pull request by HydeHunter2**
Fixes a bug discussed by email.

### Changes
- The parser of images becomes more secure.

----
UUID: af1477b6-509a-4611-b851-d7a8e3a9c02a

### CODE REVIEW

**Comment by crookedneighbor** [comment]
This is the dist file compiled for the browser, not the src files.

**Comment by crookedneighbor** [comment]
The piece you changed in the dist file is part of the underlying markdown library. See https://github.com/markdown-it/markdown-it/blob/1ad3aec2041cd2defa7e299543cc1e42184b680d/lib/rules_inline/image.js#L129-L147

**Comment by HydeHunter2** [comment]
> @crookedneighbor -- The piece you changed in the dist file is part of the underlying markdown library...

Yes. It is. But the bug occurs only in `habitica-markdown`, not in `markdown-it`. So I update the dist file in `habitica-markdown`.

> ... See https://github.com/markdown-it/markdown-it/blob/1ad3aec2041cd2defa7e299543cc1e42184b680d/lib/rules_inline/image.js#L129-L147

You have sent a link to the src file in `markdown-it`, but it works fine (I don’t know why the bug is only in `habitica-markdown`, although `markdown-it` and `habitica-markdown` image parsers are same)

I see 2 ways to fix the bug:
1. Accept my changes.
2. Upgrade to the latest `markdown-it` version.

Sorry if I misunderstood you :[

**Comment by crookedneighbor** [comment]
Your change simply won’t work though. The next time this library is built, and a new dist file is generated, your change will be removed. 

Upgrading the underlying library seems to be the better approach IMO

**Comment by HydeHunter2** [comment]
> ... your change will be removed.

I didn't know it
Thanks for the explanation.

**Pull request closed without merging**
