### PR TITLE
Issue 86 - Highlight-mentions as a markdown-it plugin

### LINKED ISSUE #86: Add user-mention highlighting markdown-it plugin to simplify markdown rendering
Currently highlighting and linking users is done separate from all the other reasoning about markdown rendering. This has led to two different locations reasoning about the same logical process with only blackbox knowledge of each other.

This has led to several issues like https://github.com/HabitRPG/habitica/issues/11504, https://github.com/HabitRPG/habitica/issues/12033 and https://github.com/HabitRPG/habitica/issues/10924

What I think should be done is add a new inline parsing rule [before](https://markdown-it.github.io/markdown-it/#Ruler.before) the [strikethrough rule](https://github.com/markdown-it/markdown-it/blob/575cfeab8acd2d59d637e856d3a205c6e81419cb/lib/parser_inline.js#L20) that creates a new `'mention'` parsing token (that is self-closing, has no sub-tokens and has the mention as content) if it is not preceded by an open link or code block token.

Then a new rendering rule should also be added that generates the span from these tokens. In order to determine whether to add the `at-highlight` class user-name and display-name should be added to the `env` (See also: https://markdown-it.github.io/markdown-it/#MarkdownIt.render) when calling render.

### PR DESCRIPTION
**Pull request by benkelaar**
Fixes #86 

Pull request to integrate mention highlighting into the markdown parser.

-----
UUID: d71d2c57-a73d-4591-b64d-e688584a9092

### CODE REVIEW

**Comment by benkelaar** [comment]
This mention plugin is now ready for review.

There are a couple of things that could still be improved but in the basis I believe this will cover the required functionality in a more resilient way than the highlightUsers function currently does in the main habitica codebase.

Things that still need to be done:
  1. Refactor into plugin format so that this can also be applied with the `.use` function
  2. Investigate if we can get the same behaviour by using https://github.com/sergiodxa/markdown-it-mentions (or alternatively https://github.com/quartzy/markdown-it-mentions but that shows less promise).
  3. Investigate if we can capture the logic by using the https://soapbox.github.io/linkifyjs/docs/plugin-mention.html plugin.

**Comment by benkelaar** [comment]
Alright, I've done point 1 from the above comment, which also lead me to a great simplification which made the code a lot better (Using linkify also to recognise e-mail addresses).

Both the other mention plugins need significant work (and have dubious support status) before they can be used for our purpose, letting that option go for now.

The linkify-mention plugin would now only replace the `/@[\w-]+` regex, which is not worth the trouble (And not even sure whether that would actually include dashes). So I think this plugin is now all good. 

Only thing that might be a good idea is to move it to a separate project like the habitica-markdown-emoji plugin, but that's up to the core team.

**Comment by benkelaar** [comment]
@paglias As discussed in Aspiring Blacksmiths guild, not moving to separate project. Let me know if you want me to squash the commits.

**Comment by paglias** [comment]
Thanks @benkelaar ! After seeing the changes I agree that a v2 release is a good idea since the html output is changed. 

Looks like the travis is not running tests and is also super out of date regarding the node version... we should move to github actions like for the main habitica repo

**Comment by benkelaar** [comment]
Yeah definitely. Not being so familiar with node made this repository rather confusing for me. I still don't understand why the tests do support `const` and whatnot but the code does not. 

Might also be an artifact of how I run it locally, please let me know if I did something wrong.

I'll bump the version up to 2.0.0 and update the main merge request as well.

**Comment by benkelaar** [comment]
BTW I'm now thinking it would be good to expose the `partOfLinkOrEmail` method on the export (similar to `unsafeHtmlRender`) so the backend can use the same logic to prevent link injection into existing links.

**Comment by paglias** [comment]
@benkelaar this one looks good but I'd like to add to the README.md file an example on how to use the mention plugins and what it does. And also a CHANGELOG.md file with the list of breaking changes in v2

**Comment by benkelaar** [comment]
I can add those, but I was wondering, a big change that's going to be affected due to fixing it like this is that the Vue.JS markdown directive (used e.g. in rendering tasks) will now also highlight users. Is that also desired or should we create separate entry-points (render-methods), one that does generate highlights and one that doesn't? (Or we could perhaps make it depend on env configuration, but then we'd probably still use two methods on the habitica codebase's side)

**Comment by paglias** [comment]
Good point,

I was going to say that we could `.use()` the plugin later but it's added when the instance is created so it's not possible to add it later.

I'd say multiple entry points is the way to go, so we would `import 'habitica-markdown/base'` or `import 'habitica-markdown/with-mentions'`

**Comment by benkelaar** [comment]
That's nicer than what I had in mind. How do I set that up? Is it just a matter of exporting two different markdown instances?

Also do you know if the unsafe one is still being used somewhere? Otherwise a major version bump might be a good time to get rid of it.

**Comment by paglias** [comment]
For nodejs modules you can just create different files:

- index.js exposes the default one
- noMentions exposes the instance without the mentions plugin

^ but this way we'll have to create different builds for webpack (which is possible), it might be easier to simply create 3 instance (normal, unsafe, with mentions) and expose them like the `unsafe` one is exposed now

**Comment by benkelaar** [comment]
Yeah, that's what I was initially planning to do. We could actually support both. Will look in to that, should be fun.

**Comment by benkelaar** [comment]
@paglias I gave it a try, did some major reshuffling of the code and exposed unsafe and withMentions (I think) now both as separate methods on the index markdown renderer and as own renderers importable as `habiticaMarkdown/unsafe` and `habiticaMarkdown/withMentions`. Let me know if you think that's the right way to go. If you do I'll update the tests to better match the new code structure and update the README.md with examples of how to use the different options.

**Comment by benkelaar** [comment]
~Hmm, it looks like it might work, but I'm not getting it to work locally at all.~

~@paglias Anything obvious you can see I'm doing wrong or shall I just revert the multiple-entrypoint build part?~

Hah, now it works 😸

**Comment by benkelaar** [comment]
So it works for me locally, but I'm too unfamiliar with how exactly node packaging works to tell if this would work for all use-cases. From what I can gather from the internet, the website and server would just basically get all the modules from this repository in their node_modules folder (similar to what I have locally now with my simlink to the other repository set up by the double `npm link` call).

However, I'm not sure if these new distributions would work for other usages. There is duplication of dependencies in them and I can probably resolve that using https://webpack.js.org/guides/code-splitting/#entry-dependencies but since I have no clue how this then should be used (Does it mean that websites would need multiple script tags to import them?) I'm not sure if doing that is the right call.

**Comment by paglias** [comment]
This is looking great @benkelaar !

> However, I'm not sure if these new distributions would work for other usages. There is duplication of dependencies in them and I can probably resolve that using https://webpack.js.org/guides/code-splitting/#entry-dependencies but since I have no clue how this then should be used (Does it mean that websites would need multiple script tags to import them?) I'm not sure if doing that is the right call.

The duplication of dependencies is unfortunately unavoidable when loading scripts directly in the webpage without using any module bundler. But it's only used by the chat extension which will only need the version with mentions support and hopefully it'll then switch to webpack as well so that it can load commonjs modules in future. I wouldn't spend more time on this one.

It's a bit late here so I won't merge it now, will do it tomorrow along with the NPM release so the other PR can be updated as well

**Comment by benkelaar** [comment]
@paglias I did slightly extend README.md to explain how the non-standard versions can be used. Agree that it's not necessary to restructure the tests. Coverage is decent, can always improve the matching to the existing modules in a later merge request.

**Comment by paglias** [comment]
Merged and published 2.0 to npm 🎉 thanks @benkelaar , noted in your profile

**Pull request merged**
